version: '3.7'
services:
  gitlab:
    image: gitlab/gitlab-ee:latest
    #right now only works with given hostname
    hostname: gitlab.example.com
    ports:
      - "443:443"
      - "8080:80"
      - "2222:22"
    volumes:
      - /srv/gitlab/config:/etc/gitlab:Z
      - /srv/gitlab/logs:/var/log/gitlab:Z
      - /srv/gitlab/data:/var/opt/gitlab:Z


#generate registration tocken and run docker exec -it <container id> bash
#gitlab-runner register...
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner    
    restart: always
    depends_on:
      - gitlab
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - '$GITLAB_HOME/gitlab-runner:/etc/gitlab-runner'